import type { Metadata } from "next";
import "../styles/globals.css";
import { Toaster } from "@/modules/components/ui/toaster";
import DrawerProvider from "@/providers/drawer-provider";


export const metadata: Metadata = {
  title: "Store app",
  description: "Generated by create next app",
  metadataBase: new URL(process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000")
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        {children}
        <Toaster />
        <DrawerProvider />
      </body>
    </html>
  );
}
