import type { Metadata } from "next";
import "../styles/globals.css";
import { Inter } from 'next/font/google'
import { ToastProvider } from "@/modules/components/ui/toast";


export const metadata: Metadata = {
  title: "Store app",
  description: "Generated by create next app",
  metadataBase: new URL(process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000")
};


const inter = Inter({ subsets: ['latin'] })
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        {children}

      </body>
    </html>
  );
}
